#+TITLE:	p1
[[file:../ASSIGNMENTS.org][back to all]]

* Objectives
1. To gather high-level details for your semester project.
2. To learn the workflow and submission process for homework assignments.

* Instructions
This semester you will build a discussion board.

** 1. Discussion Board Theme
Pick a specific topic or theme that discussion baord will be about.

Examples:
- DIY Projects
- Camping and Hiking
- A favorite band/sports team/destination

*Requirements*
*** 1.1: Theme of discussions taking place
*** 1.2: List 3-5 categories
*** 1.3: List 3-5 example message topics per category

** 2. User Roles
Every website expects to have users. The users all have roles. For example, if someone is logged out, they might be considered a "visitor". After they log in, they may become an "admin".

What are the roles of a discussion board?

[[https://www.phpbb.com/about/][phpBB]] is an open source discussion board. Use a demo instance of phpBB to answer the following question. [[https://www.phpbb.com/demo/][phpBB demo instructions]]

*** Preparation
**** /Before/ logging in as an admin, register as a new user.
***** Login
***** Logout
**** Log into phpBB as the admin, as described in the instructions above.
***** From within the administrative control panel, find the user you created above.
***** Find where to change the permissions for this user
***** Find the dropdown with permission types, and take note of the options.

*** Requirements
**** 2.1: What permissions are listed in the permission types for the user?
**** 2.2: For each of these permissions, describe that role in in your discussion board:
***** 2.2.a: What can that user do?
***** 2.2.b: What are some "actions" they will take?

*** Alternate Requirements (if phpBB is unavailable, or if you prefer)
A discussion board will often have the roles:
- =visitor= An anonymous or unregistered user.
- =member= A user that can participate in the discussions.
- =moderator= A =member= with access to the comments and posts of other =members=
- =admin= A user with access to administrative functions of the discussion board.

**** 2.3: Name 3 specific actions, or things the user might do, for each of the roles listed above.

** 3. Domain Name
Find a domain name that fits the theme of the website. You *do not* need to purchase the domain name, only find one.

*Requirements*
*** 3.1 What is the domain name?
*** 3.2 Explain how/where you found this domain name.
*** 3.3 What is the intended use of the TLD you chose?

* Due Date
The assignment is due by the end of the day (midnight), Thursday Sept 5th.

* Submission
Finish the work above in a file [[file:./YOURNAME.txt]].

** Answer/finish parts:
*** 1.1 - 1.3
*** 2.1 - 2.2.b /or/ 2.3
*** 3.1 - 3.3
** Plain text only.
** No Word docs, no PDFs, no RTFs.

From the directory containing your work, run the =submit= command from =onyx=.

=submit joeymazzarelli cs401 p1=
This command will pick up all files in the current directory (as well as any subdirectories recursively) and time-stamp them before transferring the combined files to the instructor’s account.
