#+TITLE:	Homework 0

[[file:../ASSIGNMENTS.org][back to all]]

* Objectives

1. To gather high-level details for your semester project.
2. To learn the workflow and submission process for homework assignments.


* Instructions

You will be creating an e-commerce website. This will not be an Amazon-like
website, but more of a specialty store. You will choose a specific industry to
sell products to a specific target audience.

** What are you selling?
Pick a specific industry that you will build an online shop for. The more personal you make it, the more enjoyable the project will be.

Examples:
- Antique Furniture
- Coffees & Teas
- Jewelry
- Musical Instruments
- Board Games and Card Games

*Requirements*
*** Type of projects being sold
*** List 3-5 categories
*** List 3-5 products per category

** Domain Name
Find a domain name that fits the theme of the website. You /do not/ need to
purchase the domain name, only find one.

*Requirements*
*** Domain Name
*** Explain how/where you found this domain name


* Submission
Finish the file [[file:./project.txt]]. Plain text. No Word docs, no PDFs, no RTFs.

From this directory, run the =submit= command from =onyx=.

=submit jmazzare cs401 p1=
This command will pick up all files in the current directory (as well as any subdirectories recursively) and time-stamp them before transferring the combined files to the instructor’s account.
